"""
    NVD API 2.0 Python API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Contact: 15080890+kannkyo@users.noreply.github.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import nvd_api
from nvd_api.api.products_api import ProductsApi  # noqa: E501


class TestProductsApi(unittest.TestCase):
    """ProductsApi unit test stubs"""

    def setUp(self):
        self.api = ProductsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_cpe_match(self):
        """Test case for get_cpe_match

        Match Criteria API  # noqa: E501
        """
        pass

    def test_get_cpes(self):
        """Test case for get_cpes

        CPE API  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
