"""
    NVD API 2.0 Python API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Contact: 15080890+kannkyo@users.noreply.github.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import nvd_api
from nvd_api.model.cve_oas_vulnerabilities_inner_cve_metrics_cvss_metric_v2_inner import CveOasVulnerabilitiesInnerCveMetricsCvssMetricV2Inner
from nvd_api.model.cve_oas_vulnerabilities_inner_cve_metrics_cvss_metric_v30_inner import CveOasVulnerabilitiesInnerCveMetricsCvssMetricV30Inner
from nvd_api.model.cve_oas_vulnerabilities_inner_cve_metrics_cvss_metric_v31_inner import CveOasVulnerabilitiesInnerCveMetricsCvssMetricV31Inner
globals()['CveOasVulnerabilitiesInnerCveMetricsCvssMetricV2Inner'] = CveOasVulnerabilitiesInnerCveMetricsCvssMetricV2Inner
globals()['CveOasVulnerabilitiesInnerCveMetricsCvssMetricV30Inner'] = CveOasVulnerabilitiesInnerCveMetricsCvssMetricV30Inner
globals()['CveOasVulnerabilitiesInnerCveMetricsCvssMetricV31Inner'] = CveOasVulnerabilitiesInnerCveMetricsCvssMetricV31Inner
from nvd_api.model.cve_oas_vulnerabilities_inner_cve_metrics import CveOasVulnerabilitiesInnerCveMetrics


class TestCveOasVulnerabilitiesInnerCveMetrics(unittest.TestCase):
    """CveOasVulnerabilitiesInnerCveMetrics unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCveOasVulnerabilitiesInnerCveMetrics(self):
        """Test CveOasVulnerabilitiesInnerCveMetrics"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CveOasVulnerabilitiesInnerCveMetrics()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
