"""
    NVD API 2.0 Python API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Contact: 15080890+kannkyo@users.noreply.github.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import nvd_api
from nvd_api.model.cpe_oas_products_inner_cpe_deprecated_by_inner import CpeOasProductsInnerCpeDeprecatedByInner
from nvd_api.model.cpe_oas_products_inner_cpe_refs_inner import CpeOasProductsInnerCpeRefsInner
from nvd_api.model.cpe_oas_products_inner_cpe_titles_inner import CpeOasProductsInnerCpeTitlesInner
globals()['CpeOasProductsInnerCpeDeprecatedByInner'] = CpeOasProductsInnerCpeDeprecatedByInner
globals()['CpeOasProductsInnerCpeRefsInner'] = CpeOasProductsInnerCpeRefsInner
globals()['CpeOasProductsInnerCpeTitlesInner'] = CpeOasProductsInnerCpeTitlesInner
from nvd_api.model.cpe_oas_products_inner_cpe import CpeOasProductsInnerCpe


class TestCpeOasProductsInnerCpe(unittest.TestCase):
    """CpeOasProductsInnerCpe unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCpeOasProductsInnerCpe(self):
        """Test CpeOasProductsInnerCpe"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CpeOasProductsInnerCpe()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
