"""
    NVD API 2.0 Python API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Contact: 15080890+kannkyo@users.noreply.github.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import nvd_api
from nvd_api.model.json_schema_for_common_vulnerability_scoring_system_version31 import JSONSchemaForCommonVulnerabilityScoringSystemVersion31
globals()['JSONSchemaForCommonVulnerabilityScoringSystemVersion31'] = JSONSchemaForCommonVulnerabilityScoringSystemVersion31
from nvd_api.model.cve_oas_vulnerabilities_inner_cve_metrics_cvss_metric_v31_inner import CveOasVulnerabilitiesInnerCveMetricsCvssMetricV31Inner


class TestCveOasVulnerabilitiesInnerCveMetricsCvssMetricV31Inner(unittest.TestCase):
    """CveOasVulnerabilitiesInnerCveMetricsCvssMetricV31Inner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCveOasVulnerabilitiesInnerCveMetricsCvssMetricV31Inner(self):
        """Test CveOasVulnerabilitiesInnerCveMetricsCvssMetricV31Inner"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CveOasVulnerabilitiesInnerCveMetricsCvssMetricV31Inner()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
