"""
    NVD API 2.0 Python API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Contact: 15080890+kannkyo@users.noreply.github.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import nvd_api
from nvd_api.model.cpe_match_oas_match_strings_inner_matches_inner import CpeMatchOasMatchStringsInnerMatchesInner


class TestCpeMatchOasMatchStringsInnerMatchesInner(unittest.TestCase):
    """CpeMatchOasMatchStringsInnerMatchesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCpeMatchOasMatchStringsInnerMatchesInner(self):
        """Test CpeMatchOasMatchStringsInnerMatchesInner"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CpeMatchOasMatchStringsInnerMatchesInner()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
