"""
    NVD API 2.0 Python API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Contact: 15080890+kannkyo@users.noreply.github.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import nvd_api
from nvd_api.model.json_schema_for_common_vulnerability_scoring_system_version30 import JSONSchemaForCommonVulnerabilityScoringSystemVersion30
globals()['JSONSchemaForCommonVulnerabilityScoringSystemVersion30'] = JSONSchemaForCommonVulnerabilityScoringSystemVersion30
from nvd_api.model.cve_oas_vulnerabilities_inner_cve_metrics_cvss_metric_v30_inner import CveOasVulnerabilitiesInnerCveMetricsCvssMetricV30Inner


class TestCveOasVulnerabilitiesInnerCveMetricsCvssMetricV30Inner(unittest.TestCase):
    """CveOasVulnerabilitiesInnerCveMetricsCvssMetricV30Inner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCveOasVulnerabilitiesInnerCveMetricsCvssMetricV30Inner(self):
        """Test CveOasVulnerabilitiesInnerCveMetricsCvssMetricV30Inner"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CveOasVulnerabilitiesInnerCveMetricsCvssMetricV30Inner()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
