"""
    NVD API 2.0 Python API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Contact: 15080890+kannkyo@users.noreply.github.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import nvd_api
from nvd_api.api.vulnerabilities_api import VulnerabilitiesApi  # noqa: E501


class TestVulnerabilitiesApi(unittest.TestCase):
    """VulnerabilitiesApi unit test stubs"""

    def setUp(self):
        self.api = VulnerabilitiesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_cve_history(self):
        """Test case for get_cve_history

        CVE Change History API  # noqa: E501
        """
        pass

    def test_get_cves(self):
        """Test case for get_cves

        CVE API  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
