"""
    NVD API 2.0 Python API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Contact: 15080890+kannkyo@users.noreply.github.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import nvd_api
from nvd_api.model.cve_history_oas_cve_changes_inner_change import CveHistoryOasCveChangesInnerChange
globals()['CveHistoryOasCveChangesInnerChange'] = CveHistoryOasCveChangesInnerChange
from nvd_api.model.cve_history_oas_cve_changes_inner import CveHistoryOasCveChangesInner


class TestCveHistoryOasCveChangesInner(unittest.TestCase):
    """CveHistoryOasCveChangesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCveHistoryOasCveChangesInner(self):
        """Test CveHistoryOasCveChangesInner"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CveHistoryOasCveChangesInner()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
