"""
    NVD API 2.0 Python API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Contact: 15080890+kannkyo@users.noreply.github.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import nvd_api
from nvd_api.model.cve_history_oas_cve_changes_inner_change_details_inner import CveHistoryOasCveChangesInnerChangeDetailsInner
globals()['CveHistoryOasCveChangesInnerChangeDetailsInner'] = CveHistoryOasCveChangesInnerChangeDetailsInner
from nvd_api.model.cve_history_oas_cve_changes_inner_change import CveHistoryOasCveChangesInnerChange


class TestCveHistoryOasCveChangesInnerChange(unittest.TestCase):
    """CveHistoryOasCveChangesInnerChange unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCveHistoryOasCveChangesInnerChange(self):
        """Test CveHistoryOasCveChangesInnerChange"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CveHistoryOasCveChangesInnerChange()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
