"""
    NVD API 2.0 Python API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Contact: 15080890+kannkyo@users.noreply.github.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import nvd_api
from nvd_api.model.cve_oas_vulnerabilities_inner_cve_configurations_inner import CveOasVulnerabilitiesInnerCveConfigurationsInner
from nvd_api.model.cve_oas_vulnerabilities_inner_cve_descriptions_inner import CveOasVulnerabilitiesInnerCveDescriptionsInner
from nvd_api.model.cve_oas_vulnerabilities_inner_cve_metrics import CveOasVulnerabilitiesInnerCveMetrics
from nvd_api.model.cve_oas_vulnerabilities_inner_cve_references_inner import CveOasVulnerabilitiesInnerCveReferencesInner
from nvd_api.model.cve_oas_vulnerabilities_inner_cve_vendor_comments_inner import CveOasVulnerabilitiesInnerCveVendorCommentsInner
from nvd_api.model.cve_oas_vulnerabilities_inner_cve_weaknesses_inner import CveOasVulnerabilitiesInnerCveWeaknessesInner
globals()['CveOasVulnerabilitiesInnerCveConfigurationsInner'] = CveOasVulnerabilitiesInnerCveConfigurationsInner
globals()['CveOasVulnerabilitiesInnerCveDescriptionsInner'] = CveOasVulnerabilitiesInnerCveDescriptionsInner
globals()['CveOasVulnerabilitiesInnerCveMetrics'] = CveOasVulnerabilitiesInnerCveMetrics
globals()['CveOasVulnerabilitiesInnerCveReferencesInner'] = CveOasVulnerabilitiesInnerCveReferencesInner
globals()['CveOasVulnerabilitiesInnerCveVendorCommentsInner'] = CveOasVulnerabilitiesInnerCveVendorCommentsInner
globals()['CveOasVulnerabilitiesInnerCveWeaknessesInner'] = CveOasVulnerabilitiesInnerCveWeaknessesInner
from nvd_api.model.cve_oas_vulnerabilities_inner_cve import CveOasVulnerabilitiesInnerCve


class TestCveOasVulnerabilitiesInnerCve(unittest.TestCase):
    """CveOasVulnerabilitiesInnerCve unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCveOasVulnerabilitiesInnerCve(self):
        """Test CveOasVulnerabilitiesInnerCve"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CveOasVulnerabilitiesInnerCve()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
