"""
    NVD API 2.0 Python API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Contact: 15080890+kannkyo@users.noreply.github.com
    Generated by: https://openapi-generator.tech
"""


import os
import unittest
from pprint import pprint

from nvd_api.client import NvdApiClient


class TestGetAll(unittest.TestCase):
    def setUp(self):
        api_key = os.getenv('NVD_API_KEY')
        if api_key:
            self.client = NvdApiClient(wait_time=1 * 1000, api_key=api_key)  # noqa: E501
        else:
            self.client = NvdApiClient(wait_time=10 * 1000)  # noqa: E501

    def tearDown(self):
        pass

    def test_get_all_cpe_match(self):
        response = self.client.get_all_cpe_match(
            last_mod_start_date="2021-01-01T00:00:00.000",
            last_mod_end_date="2021-03-01T00:00:00.000"
        )
        assert (len(response.match_strings) > 5000)
        assert response.results_per_page > 5000

    def test_get_all_cpes(self):
        response = self.client.get_all_cpes(
            last_mod_start_date="2021-01-01T00:00:00.000",
            last_mod_end_date="2021-03-01T00:00:00.000"
        )
        assert (len(response.products) > 10000)
        assert response.results_per_page > 10000

    def test_get_all_cve_history(self):
        response = self.client.get_all_cve_history(
            change_start_date="2021-01-01T00:00:00.000",
            change_end_date="2021-02-15T00:00:00.000",
        )
        pprint(response)
        assert (len(response.cve_changes) > 5000)
        assert response.results_per_page > 5000

    def test_get_all_cve(self):
        response = self.client.get_all_cves(
            pub_start_date="2021-01-01T00:00:00.000",
            pub_end_date="2021-02-15T00:00:00.000",
        )
        pprint(response)
        assert (len(response.vulnerabilities) > 2000)
        assert response.results_per_page > 2000


if __name__ == '__main__':
    unittest.main()
