"""
    NVD API 2.0 Python API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Contact: 15080890+kannkyo@users.noreply.github.com
    Generated by: https://openapi-generator.tech
"""


import os
import unittest
from datetime import datetime, timedelta
from pprint import pprint

from nvd_api.client import NvdApiClient
from nvd_api.low_api.exceptions import ApiValueError


class TestCount(unittest.TestCase):
    def setUp(self):
        api_key = os.getenv('NVD_API_KEY')
        if api_key:
            self.client = NvdApiClient(wait_time=1 * 1000, api_key=api_key)  # noqa: E501
        else:
            self.client = NvdApiClient(wait_time=10 * 1000)  # noqa: E501

    def tearDown(self):
        pass

    def test_count_cpes(self):
        count = self.client.count_cpes()
        assert count >= 1000000

    def test_count_cpes_with_start_date(self):
        last_mod_start_date = datetime.now() - timedelta(days=1)
        count = self.client.count_cpes(last_mod_start_date=last_mod_start_date)
        assert count >= 1000

    def test_count_cpes_with_end_date(self):
        with self.assertRaises(ApiValueError):
            count = self.client.count_cpes(last_mod_end_date=datetime.now())
            pprint(count)

    def test_count_cpes_with_start_date_and_end_date(self):
        last_mod_end_date = datetime.now()
        last_mod_start_date = last_mod_end_date - timedelta(days=1)
        count = self.client.count_cpes(last_mod_start_date=last_mod_start_date,
                                       last_mod_end_date=last_mod_end_date)
        assert count >= 1000

    def test_count_cves(self):
        count = self.client.count_cves()
        assert count >= 200000

    def test_count_cves_with_start_date(self):
        last_mod_start_date = datetime.now() - timedelta(days=2)
        count = self.client.count_cves(last_mod_start_date=last_mod_start_date)
        assert count >= 100

    def test_count_cves_with_end_date(self):
        with self.assertRaises(ApiValueError):
            count = self.client.count_cves(last_mod_end_date=datetime.now())
            pprint(count)

    def test_count_cves_with_start_date_and_end_date(self):
        last_mod_end_date = datetime.now()
        last_mod_start_date = last_mod_end_date - timedelta(days=1)
        count = self.client.count_cves(last_mod_start_date=last_mod_start_date,
                                       last_mod_end_date=last_mod_end_date)
        assert count >= 100


if __name__ == '__main__':
    unittest.main()
