"""
    NVD API 2.0 Python API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Contact: 15080890+kannkyo@users.noreply.github.com
    Generated by: https://openapi-generator.tech
"""


import os
import unittest

from nvd_api.client import NvdApiClient


class TestGetNameOrId(unittest.TestCase):
    def setUp(self):
        api_key = os.getenv('NVD_API_KEY')
        if api_key:
            self.client = NvdApiClient(wait_time=1 * 1000, api_key=api_key)  # noqa: E501
        else:
            self.client = NvdApiClient(wait_time=10 * 1000)  # noqa: E501

    def tearDown(self):
        pass

    def test_one_cpe_match_and_several_cpe_name(self):
        cpe_names = self.client.get_cpe_name_by_cve_id(cve_id="CVE-2022-1376")
        assert len(cpe_names) >= 4

    def test_several_cpe_match_and_several_cpe_name(self):
        cpe_names = self.client.get_cpe_name_by_cve_id(cve_id="CVE-2022-28613")
        assert len(cpe_names) >= 13

    def test_one_cve_id(self):
        cve_ids = self.client.get_cve_id_by_cpe_name(
            cpe_name="cpe:2.3:a:sox_project:sox:14.4.1:*:*:*:*:*:*:*")
        assert len(cve_ids) >= 1

    def test_several_cve_id(self):
        cve_ids = self.client.get_cve_id_by_cpe_name(
            cpe_name="cpe:2.3:a:deltaww:diaenergie:1.8.02.004:*:*:*:*:*:*:*")
        assert len(cve_ids) >= 14

    def test_two_same_cwe_id(self):
        cwe_id = self.client.get_cwe_id_by_cve_id(cve_id="CVE-2021-36778")
        assert cwe_id == ["CWE-863"]

    def test_two_different_cwe_id(self):
        cwe_id = self.client.get_cwe_id_by_cve_id(cve_id="CVE-2021-3643")
        assert cwe_id == ["CWE-120", "CWE-125"]


if __name__ == '__main__':
    unittest.main()
