"""
    NVD API 2.0 Python API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Contact: 15080890+kannkyo@users.noreply.github.com
    Generated by: https://openapi-generator.tech
"""


import time
import unittest

from nvd_api.client import NvdApiClient


class TestGetCpes(unittest.TestCase):
    def setUp(self):
        pass

    def tearDown(self):
        pass

    def test_sleep_with_wait_time(self):
        client = NvdApiClient(wait_time=1000)
        start = time.time()
        client._sleep(1000)
        end = time.time()

        duration = end - start
        assert duration >= 1

    def test_sleep_without_wait_time(self):
        client = NvdApiClient(wait_time=1000)
        time.sleep(1.1)
        start = time.time()
        client._sleep()
        end = time.time()

        duration = end - start
        assert duration <= 0.1


if __name__ == '__main__':
    unittest.main()
