"""
    NVD API 2.0 Python API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Contact: 15080890+kannkyo@users.noreply.github.com
    Generated by: https://openapi-generator.tech
"""


import unittest

from client import NvdApiClient


class TestGetCpes(unittest.TestCase):
    def setUp(self):
        self.client = NvdApiClient()  # noqa: E501

    def tearDown(self):
        pass

    def test_sleep(self):
        self.client._sleep(10)


if __name__ == '__main__':
    unittest.main()
