# coding: utf-8

"""
    NVD API 2.0 Python API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Contact: 15080890+kannkyo@users.noreply.github.com
    Generated by: https://openapi-generator.tech
"""

import unittest

import nvd_api
from nvd_api.model.cve_history_oas import CveHistoryOas
from nvd_api import configuration


class TestCveHistoryOas(unittest.TestCase):
    """CveHistoryOas unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
