# flake8: noqa

"""
    NVD API 2.0 Python API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Contact: 15080890+kannkyo@users.noreply.github.com
    Generated by: https://openapi-generator.tech
"""


__version__ = "1.0.0"

# import NvdApiClient
from nvd_api.client import VERSION_TYPE
from nvd_api.client import CVSS_V2_SEVERITY
from nvd_api.client import CVSS_V3_SEVERITY
from nvd_api.client import EVENT_NAME
from nvd_api.client import NvdApiClient
