@startuml

hide circle
hide empty members
hide empty methods

package docker {
  class "docker-ci" as docker_ci <<workflow>>
  class "docker-publish" as docker_publish <<workflow>>
  class "docker-setup" as docker_setup <<action>>

  docker_ci ..> docker_setup
  docker_publish ..> docker_setup
}

package python {
  class "python-ci" as python_ci <<workflow>>
  class "python-publish" as python_publish <<workflow>>
  class "python-setup" as python_setup <<action>>

  python_ci ..> python_setup
  python_publish ..> python_setup
}

package common {
  class "auto-pr-review" <<workflow>>
  class "scorecards" <<workflow>>
}

@enduml