# coding: utf-8

"""
    NVD API 2.0 Python API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Contact: 15080890+kannkyo@users.noreply.github.com
    Generated by: https://openapi-generator.tech
"""

from nvd_api.paths.cpematch_2_0_.get import GetCpeMatch
from nvd_api.paths.cpes_2_0_.get import GetCpes


class ProductsApi(
    GetCpeMatch,
    GetCpes,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
