@startuml 

title docker-setup

start 

:sigstore/cosign-installer;
note right: cosignをインストール

:docker/setup-qemu-action;
note right: QEMUを設定

:docker/setup-buildx-action;
note right: docker buildxを設定

stop

@enduml
