@startuml 

title python-setup

start 

:actions/setup-python;
note right: pythonを設定

:snok/install-poetry;
note right: poetryをインストール

:actions/cache;
note right: .venvをキャッシュ

:poetry install;
note right: 依存関係をインストール

stop

@enduml
