@startuml 

title python-publish-summary

start 

if (workflow_dispatch ?) then (yes)
elseif (push to main branch ?) then (yes)
elseif (push to tags like "v*.*.*" ?) then (yes)
else (no)
  stop
endif

:dockerize;

stop

@enduml
